### ISSUE TITLE
Warning: a promise was created in a handler | putAsync

### ISSUE THREAD

**Issue by PavlosIsaris** [woocommerce/wc-api-node#76]
Hi, I am trying to perform a PUT request and return it's result as following:

```
  putData(url: string, putData: any): Promise<any> {
    return new Promise((resolve, reject) => {
      this.WooCommerce.putAsync(url, putData)
        .then((data: any) => {
          console.log("put success");
          resolve((JSON.parse(data.toJSON().body)));
        }, error => {
          reject(error)
        }).catch((error: Error) => {
        reject(error);
      });
    });
  }
```
This works correctly and I am able to get the resolved Data. However, I receive the following **warning** (not error):

```
Warning: a promise was created in a handler at file:///android_asset/www/build/vendor.js:174390:22 but was not returned from it, see http://goo.gl/rRqMUw
    at WooCommerceAPI.promisified [as putAsync] (file:///android_asset/www/build/vendor.js:209577:17)
    at Request.self.callback (file:///android_asset/www/build/vendor.js:174390:22)
    at Request.EventEmitter.emit (file:///android_asset/www/build/vendor.js:63589:17)
    at Request.<anonymous> (file:///android_asset/www/build/vendor.js:175367:10)
    at Request.EventEmitter.emit (file:///android_asset/www/build/vendor.js:63586:17)
    at .<anonymous> (file:///android_asset/www/build/vendor.js:175289:12)
    at g (file:///android_asset/www/build/vendor.js:63670:16)
    at EventEmitter.emit (file:///android_asset/www/build/vendor.js:63601:20)
From previous event:
    at WoocommerceApiProvider.webpackJsonp.425.WoocommerceApiProvider.putData (file:///android_asset/www/build/main.js:1152:33)
    at SafeSubscriber._complete (file:///android_asset/www/build/main.js:1113:27)
    at SafeSubscriber.__tryOrUnsub (file:///android_asset/www/build/vendor.js:17283:16)
    at SafeSubscriber.complete (file:///android_asset/www/build/vendor.js:17268:26)
    at Subscriber._complete (file:///android_asset/www/build/vendor.js:17181:26)
    at Subscriber.complete (file:///android_asset/www/build/vendor.js:17163:18)
    at SafeSubscriber._next (file:///android_asset/www/build/main.js:55:26)
    at SafeSubscriber.__tryOrUnsub (file:///android_asset/www/build/vendor.js:17283:16)
    at SafeSubscriber.next (file:///android_asset/www/build/vendor.js:17232:22)
    at Subscriber._next (file:///android_asset/www/build/vendor.js:17174:26)
    at Subscriber.next (file:///android_asset/www/build/vendor.js:17138:18)
    at file:///android_asset/www/build/main.js:1127:30
    at Request.self.callback (file:///android_asset/www/build/vendor.js:174390:22)
From previous event:
    at Observable._subscribe (file:///android_asset/www/build/main.js:1126:22)
    at Observable._trySubscribe (file:///android_asset/www/build/vendor.js:211:25)
    at Observable.subscribe (file:///android_asset/www/build/vendor.js:199:27)
    at Observable._subscribe (file:///android_asset/www/build/main.js:50:24)
    at Observable._trySubscribe (file:///android_asset/www/build/vendor.js:211:25)
    at Observable.subscribe (file:///android_asset/www/build/vendor.js:199:27)
    at Observable._subscribe (file:///android_asset/www/build/main.js:1104:53)
    at Observable._trySubscribe (file:///android_asset/www/build/vendor.js:211:25)
    at Observable.subscribe (file:///android_asset/www/build/vendor.js:199:27)
    at new ProfilePage (file:///android_asset/www/build/0.js:245:98)
    at createClass (file:///android_asset/www/build/vendor.js:11299:26)
    at createDirectiveInstance (file:///android_asset/www/build/vendor.js:11125:37)
    at createViewNodes (file:///android_asset/www/build/vendor.js:12475:49)
    at createRootView (file:///android_asset/www/build/vendor.js:12380:5)
    at callWithDebugContext (file:///android_asset/www/build/vendor.js:13511:42)
    at Object.debugCreateRootView [as createRootView] (file:///android_asset/www/build/vendor.js:12972:12)
    at ComponentFactory_.create (file:///android_asset/www/build/vendor.js:10316:46)
    at ComponentFactoryBoundToModule.create (file:///android_asset/www/build/vendor.js:3931:29)
    at NavControllerBase._viewInit (file:///android_asset/www/build/vendor.js:61769:44)
```

**Comment by claudiosanches** [comment]
This library is now deprecated, you should try https://github.com/woocommerce/woocommerce-rest-api-js-lib
